# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
