# GoReleaser configuration
# https://goreleaser.com/customization/

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: vc-jump
    main: ./cmd/vc-jump
    binary: vc-jump
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*
      - config.example.yaml

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Security Updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other'
      order: 999

release:
  github:
    owner: Veritas-Calculus
    name: vc-jump
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## vc-jump {{ .Tag }}

    Secure SSH bastion server with session recording and audit logging.
  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}

# Docker support (optional)
# dockers:
#   - image_templates:
#       - "ghcr.io/veritas-calculus/vc-jump:{{ .Tag }}"
#       - "ghcr.io/veritas-calculus/vc-jump:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
